//
//  Constants.swift
//  Hako
//
//  Created by Gao Tianrun on 30/11/25.
//

struct Constants {
    static let seasons = ["winter", "spring", "summer", "fall"]
    
    // Since genres should not change much, I have decided to hard code this instead of relying on Jikan API genres endpoint
    static let animeGenres = [
        1: "Action",
        2: "Adventure",
        5: "Avant Garde",
        46: "Award Winning",
        28: "Boys Love",
        4: "Comedy",
        8: "Drama",
        10: "Fantasy",
        26: "Girls Love",
        47: "Gourmet",
        14: "Horror",
        7: "Mystery",
        22: "Romance",
        24: "Sci-Fi",
        36: "Slice Of Life",
        30: "Sports",
        37: "Supernatural",
        41: "Suspense",
        9: "Ecchi",
        49: "Erotica",
    ]
    static let animeThemes = [
        50: "Adult Cast",
        51: "Anthropomorphic",
        52: "CGDCT",
        53: "Childcare",
        54: "Combat Sports",
        81: "Crossdressing",
        55: "Delinquents",
        39: "Detective",
        56: "Educational",
        57: "Gag Humour",
        58: "Gore",
        35: "Harem",
        59: "High Stakes Game",
        13: "Historical",
        60: "Idols (Female)",
        61: "Idols (Male)",
        62: "Isekai",
        63: "Iyashikei",
        64: "Love Polygon",
        65: "Magical Sex Shift",
        66: "Mahou Shoujo",
        17: "Martial Arts",
        18: "Mecha",
        67: "Medical",
        38: "Military",
        19: "Music",
        6: "Mythology",
        68: "Organised Crime",
        69: "Otaku Culture",
        20: "Parody",
        70: "Performing Arts",
        71: "Pets",
        40: "Psychological",
        3: "Racing",
        72: "Reincarnation",
        73: "Reverse Harem",
        74: "Love Status Quo",
        21: "Samurai",
        23: "School",
        75: "Showbiz",
        29: "Space",
        11: "Strategy Game",
        31: "Super Power",
        76: "Survival",
        77: "Team Sports",
        78: "Time Travel",
        32: "Vampire",
        79: "Video Game",
        80: "Visual Arts",
        48: "Workplace",
        82: "Urban Fantasy",
        83: "Villainess",
    ]
    static let animeDemographics = [
        43: "Josei",
        15: "Kids",
        42: "Seinen",
        25: "Shoujo",
        27: "Shounen",
    ]
    
    static let mangaGenres = [
        1: "Action",
        2: "Adventure",
        5: "Avant Garde",
        46: "Award Winning",
        28: "Boys Love",
        4: "Comedy",
        8: "Drama",
        10: "Fantasy",
        26: "Girls Love",
        47: "Gourmet",
        14: "Horror",
        7: "Mystery",
        22: "Romance",
        24: "Sci-Fi",
        36: "Slice Of Life",
        30: "Sports",
        37: "Supernatural",
        45: "Suspense",
        9: "Ecchi",
        49: "Erotica",
    ]
    static let mangaThemes = [
        50: "Adult Cast",
        51: "Anthropomorphic",
        52: "CGDCT",
        53: "Childcare",
        54: "Combat Sports",
        44: "Crossdressing",
        55: "Delinquents",
        39: "Detective",
        56: "Educational",
        57: "Gag Humour",
        58: "Gore",
        35: "Harem",
        59: "High Stakes Game",
        13: "Historical",
        60: "Idols (Female)",
        61: "Idols (Male)",
        62: "Isekai",
        63: "Iyashikei",
        64: "Love Polygon",
        65: "Magical Sex Shift",
        66: "Mahou Shoujo",
        17: "Martial Arts",
        18: "Mecha",
        67: "Medical",
        38: "Military",
        19: "Music",
        6: "Mythology",
        69: "Organised Crime",
        70: "Otaku Culture",
        20: "Parody",
        71: "Performing Arts",
        72: "Pets",
        40: "Psychological",
        3: "Racing",
        73: "Reincarnation",
        74: "Reverse Harem",
        75: "Love Status Quo",
        21: "Samurai",
        23: "School",
        76: "Showbiz",
        29: "Space",
        11: "Strategy Game",
        31: "Super Power",
        77: "Survival",
        78: "Team Sports",
        79: "Time Travel",
        32: "Vampire",
        80: "Video Game",
        81: "Villainess",
        82: "Visual Arts",
        48: "Workplace",
        83: "Urban Fantasy",
    ]
    static let mangaDemographics = [
        42: "Josei",
        15: "Kids",
        41: "Seinen",
        25: "Shoujo",
        27: "Shounen",
    ]
    
    static let scoreLabels = [
        "0 - Not yet scored",
        "1 - Appalling",
        "2 - Horrible",
        "3 - Very bad",
        "4 - Bad",
        "5 - Average",
        "6 - Fine",
        "7 - Good",
        "8 - Very good",
        "9 - Great",
        "10 - Masterpiece"
    ]
}
